### ISSUE TITLE
Hover and click highlighting for selection/radio fields gets confusing

### ISSUE THREAD

**Issue by empicano** [fastsurvey/frontend#47]
When filling out the `selection` and `radio` fields I found it a bit difficult to know what is selected. The first issue was that when clicking on an option to unselect it, it's very difficult to see the font color change in the text. It got only clear afterwards, when the border vanishes when clicking somewhere else:

<img src="https://user-images.githubusercontent.com/26978146/117450167-2ac1a180-af41-11eb-98ea-a2383a4f7e3a.gif" width="500">

The other thing that I found was that more than one option can be highlighted when using keyboard and mouse together, which could give the impression that multiple fields are selected:

<img src="https://user-images.githubusercontent.com/26978146/117450253-44fb7f80-af41-11eb-8daf-8f6fbe9412bb.gif" width="500">

In general I found the combination of border and background color highlighting a bit difficult to decipher, maybe something like light background color change for hover, and then more saturated color change once selected could work?

**Comment by dostuffthatmatters** [comment]
Good points! Will fix that 👍

**Comment by dostuffthatmatters** [comment]
@empicano I have updated these fields. Now there is also an check-icon and I am only using the ring for focus (not also for selected)

Have a look :) https://dev.fastsurvey.io/dostuffthatmatters/hilarious-crocodile

**Comment by empicano** [comment]
Very nice! Now it's a lot clearer what's selected and what's in focus 😎
