### ISSUE TITLE
Blur effect on "coming soon ..." links works in Chrome/Safari but not in Firefox

### ISSUE THREAD

**Issue by empicano** [fastsurvey/frontend#67]
https://user-images.githubusercontent.com/26978146/133600093-208d1dd9-9b3a-4b9c-86b0-9507155e8fc6.mov

**Comment by dostuffthatmatters** [comment]
Oh, thank you :)

Cross-browser differences are annoying ^^

**Comment by empicano** [comment]
I can imagine 😅
