### ISSUE TITLE
Handle links to console/frontend/backend over environment variables

### ISSUE THREAD

**Issue by empicano** [fastsurvey/frontend#75]
The login button on the _development_ landing page points to the _production_ console, probably that's more fault-proof if the links are generated using environment variables, roughly like: `console.{ENVIRONMENT}.fastsurvey.de`

**Comment by dostuffthatmatters** [comment]
Yes, they handled over env variables, already but only for the backend communication, not for the UI.

But, I will do that for the UI as well.
